### ISSUE TITLE
At first the website worked but now it's not

### ISSUE THREAD

**Issue by vatsal20001** [OshekharO/jiomart-coupon-checker#26]
When first time I entered all details like cart if and auth toke, it was running correctly and showing correct status like coupon cannot be applied anymore.
But now it's not working and showing only invalid and status unknown for even same codes.
Tell me correct way to do it 
Also how much time it takes to generate a code

**Comment by OshekharO** [comment]
Show me response

**Comment by h7aini** [comment]
I'm curious.
Instead can we try cracking md5?
or is there any way to skip rate limit?

**Comment by OshekharO** [comment]
> I'm curious. Instead can we try cracking md5? or is there any way to skip rate limit?

I have already implemented rate limiting bypass

**Comment by h7aini** [comment]
@OshekharO were you able to crack working code?
bcz i'm still seeing not valid anymore. 
Also, for rate limit, After 3-4 attempts i'm getting status as Unknown.

**Comment by vatsal20001** [comment]
> > I'm curious. Instead can we try cracking md5? or is there any way to skip rate limit?
> 
> I have already implemented rate limiting bypass

How

**Comment by vatsal20001** [comment]
> Show me response

<img width="720" height="1640" alt="Image" src="https://github.com/user-attachments/assets/ce553ff2-a1b0-4d75-b78c-704d7f577794" />

**Comment by vatsal20001** [comment]
> Show me response

Previously it was showing coupon cannot be applied anymore or coupon invalid cannot be applied in status too but only showing invalid now
